services:
  - type: web
    name: expense-tracker
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
